/**
 * Control system types.
 *
 * The control system manages the orchestrator/ecosystem spectrum.
 * It provides checkpoints, mode shift recommendations, and the
 * control topology visualization from the blog post.
 *
 * "Not a static PM tool, not a static control model, but an adaptive
 * control system that shifts management style based on observed
 * project dynamics."
 */

import type { ControlMode, ProjectPhase, RiskLevel, DomainExpertise, TeamMaturity } from './project.js';

/**
 * A checkpoint gate that pauses agent execution until human review.
 * Checkpoints are configurable — more in orchestrator mode, fewer
 * in ecosystem mode.
 *
 * Examples from the blog post:
 * - Phase transition
 * - High-risk artifact touch
 * - Before merge
 * - Daily summary
 */
export interface Checkpoint {
  id: string;
  /** Human-readable name for this checkpoint. */
  name: string;
  /** What triggers this checkpoint. */
  trigger: 'phase_transition' | 'high_risk_touch' | 'before_merge' | 'daily_summary' | 'custom';
  /** Detailed description of when this checkpoint fires. */
  description: string;
  /** Whether this checkpoint is currently active. */
  enabled: boolean;
  /** Custom trigger condition (when trigger is 'custom'). */
  customCondition: string | null;
}

/**
 * A single point on the control topology spectrum.
 * The blog post shows bar charts with the spectrum from
 * Orchestrator to Ecosystem across four dimensions.
 *
 * Value is 0-100 where 0 = full orchestrator, 100 = full ecosystem.
 */
export interface ControlTopologyPoint {
  /** The dimension this point represents. */
  dimension: 'phase' | 'risk' | 'domain_expertise' | 'team_maturity';
  /** Human-readable label for the current position. */
  label: string;
  /** Current position on the spectrum (0 = orchestrator, 100 = ecosystem). */
  currentPosition: number;
  /** System-recommended position on the spectrum. */
  recommendedPosition: number;
}

/**
 * System recommendation to shift the control mode.
 * Generated by the topology engine when project signals suggest
 * the current mode isn't optimal.
 *
 * "This task touches the payments system. I've shifted to Orchestrator
 * mode and added a mandatory review gate."
 */
export interface ModeShiftRecommendation {
  id: string;
  /** What mode the system recommends shifting to. */
  recommendedMode: ControlMode;
  /** Current mode for comparison. */
  currentMode: ControlMode;
  /** Why the system is recommending this shift. */
  rationale: string;
  /** What signals triggered this recommendation. */
  signals: ModeShiftSignal[];
  /** Whether the human has acted on this recommendation. */
  status: 'pending' | 'accepted' | 'rejected';
  /** Tick when this recommendation was generated. */
  createdAtTick: number;
}

/**
 * A signal that contributes to a mode shift recommendation.
 * Multiple signals are combined to form the recommendation.
 */
export interface ModeShiftSignal {
  /** What metric or observation this signal is based on. */
  source: string;
  /** The observed value or condition. */
  observation: string;
  /** How strongly this signal pushes toward the recommendation. */
  weight: number;
}

/**
 * The throughput vs. quality dial. An explicit tradeoff control
 * that influences how aggressively agents work and how much
 * review gating is applied.
 *
 * "I need this fast" vs. "I need this right."
 */
export interface ThroughputQualityBias {
  /**
   * Position on the spectrum (0-100).
   * 0 = maximum quality focus (slower, more review gates)
   * 100 = maximum throughput (faster, fewer gates)
   */
  value: number;
}

/**
 * Full control configuration for a project. Combines the mode,
 * topology, checkpoints, and throughput/quality bias.
 */
export interface ControlConfig {
  /** Active control mode. */
  mode: ControlMode;
  /** Current topology across all four dimensions. */
  topology: ControlTopologyPoint[];
  /** Active checkpoints. */
  checkpoints: Checkpoint[];
  /** Throughput vs. quality setting. */
  bias: ThroughputQualityBias;
  /** Whether risk-aware gating is enabled. */
  riskAwareGating: boolean;
  /** Pending mode shift recommendations. */
  pendingRecommendations: ModeShiftRecommendation[];
}

/**
 * Parameters used by the topology engine to compute recommended
 * control positions. Derived from project state.
 */
export interface TopologyInput {
  phase: ProjectPhase;
  riskLevel: RiskLevel;
  domainExpertise: DomainExpertise;
  teamMaturity: TeamMaturity;
}
